--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2023. 02. 24. 10:47:37
-- Server version: 5.5.5-10.4.24-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE sportverseny;

--
-- Drop table `teamrace`
--
DROP TABLE IF EXISTS teamrace;

--
-- Drop table `competitionnumbers`
--
DROP TABLE IF EXISTS competitionnumbers;

--
-- Drop table `users`
--
DROP TABLE IF EXISTS users;

--
-- Drop table `teams`
--
DROP TABLE IF EXISTS teams;

--
-- Drop table `races`
--
DROP TABLE IF EXISTS races;

--
-- Set default database
--
USE sportverseny;

--
-- Create table `races`
--
CREATE TABLE races (
  id INT(11) NOT NULL AUTO_INCREMENT,
  raceName VARCHAR(255) DEFAULT NULL,
  raceDateFrom DATETIME DEFAULT NULL,
  raceDateUpTo DATETIME DEFAULT NULL,
  institution VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `teams`
--
CREATE TABLE teams (
  id INT(11) NOT NULL AUTO_INCREMENT,
  RaceId INT(11) DEFAULT NULL,
  temamName VARCHAR(255) DEFAULT NULL,
  Institution VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create foreign key
--
ALTER TABLE teams 
  ADD CONSTRAINT FK_teams_races_id FOREIGN KEY (RaceId)
    REFERENCES races(id);

--
-- Create table `users`
--
CREATE TABLE users (
  id INT(11) NOT NULL,
  firstName VARCHAR(255) DEFAULT NULL,
  lastName VARCHAR(255) DEFAULT NULL,
  gender VARCHAR(255) DEFAULT NULL,
  userName VARCHAR(255) DEFAULT NULL,
  email VARCHAR(50) DEFAULT NULL,
  password VARCHAR(255) DEFAULT NULL,
  number INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `competitionnumbers`
--
CREATE TABLE competitionnumbers (
  id INT(11) NOT NULL AUTO_INCREMENT,
  raceNumber VARCHAR(255) DEFAULT NULL,
  weighting INT(11) DEFAULT NULL,
  moreIsBetter INT(11) DEFAULT NULL,
  type INT(11) DEFAULT NULL,
  userId INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create foreign key
--
ALTER TABLE competitionnumbers 
  ADD CONSTRAINT FK_competitionnumbers_users_id FOREIGN KEY (userId)
    REFERENCES users(id);

--
-- Create table `teamrace`
--
CREATE TABLE teamrace (
  teamId INT(11) NOT NULL,
  competitionNumberId INT(11) NOT NULL,
  resultNumber DECIMAL(10, 0) DEFAULT NULL,
  resultTime TIME DEFAULT NULL,
  PRIMARY KEY (teamId, competitionNumberId)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create foreign key
--
ALTER TABLE teamrace 
  ADD CONSTRAINT FK_teamrace_competitionnumbers_id FOREIGN KEY (competitionNumberId)
    REFERENCES competitionnumbers(id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE teamrace 
  ADD CONSTRAINT FK_teamrace_teams_id FOREIGN KEY (teamId)
    REFERENCES teams(id) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- 
-- Dumping data for table races
--
-- Table sportverseny.races does not contain any data (it is empty)

-- 
-- Dumping data for table users
--
-- Table sportverseny.users does not contain any data (it is empty)

-- 
-- Dumping data for table teams
--
-- Table sportverseny.teams does not contain any data (it is empty)

-- 
-- Dumping data for table competitionnumbers
--
-- Table sportverseny.competitionnumbers does not contain any data (it is empty)

-- 
-- Dumping data for table teamrace
--
-- Table sportverseny.teamrace does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;